version: '3.1'

networks:
    development:
        driver: overlay

services:
    replicated-service:
        deploy:
            mode: replicated
            replicas: 8
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: pause
                monitor: 10s
                max_failure_ratio: 0
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        image: redis:3.0.7
        networks:
            - development
        ports:
            - "6379"
