version: '3.1'

services:
    global-service:
        command: ["ping", "docker.com"]
        deploy:
            mode: global
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: pause
                monitor: 10s
                max_failure_ratio: 0
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        image: alpine:latest
        networks:
            - development 
